### ISSUE TITLE
refmap is not getting generated during `build` task

### ISSUE THREAD

**Issue by Zergatul** [AxstSoftware/ForgeMixins#4]
I tried to start from fresh repo, ran `gradlew build` (no other tasks ran before), `JAVA_HOME` set to `jdk1.8.0_202`. Resulting jar has no refmap. Seeing this in the log:
```
> Task :compileJava
Potential refmap conflict. Duplicate refmap name mixins.examplemod.refmap.json specified for sourceSet main, already defined for sourceSet main
```

**Comment by Zergatul** [comment]
Found fix in this fork: https://github.com/PumpkinXD/ForgeMixins

**Comment by sdxqw** [comment]
Dont make issues this project its not maintained anymore.
